{
 "title": "Okteto Insights",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Nodes Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "% memory used from total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(okteto_system_node_memory_usage_bytes / okteto_system_node_memory_bytes) * 100",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "% memory requested from total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(okteto_system_node_memory_requested_bytes / okteto_system_node_memory_bytes) * 100",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "% memory used from requested",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(okteto_system_node_memory_usage_bytes / okteto_system_node_memory_requested_bytes) * 100",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "Nodes CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "% used CPU from total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(okteto_system_node_cpu_usage_cores / okteto_system_node_cpu_cores) * 100",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "% requested CPU from total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(okteto_system_node_cpu_requested_cores / okteto_system_node_cpu_cores) * 100",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "% used from requested",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(okteto_system_node_cpu_usage_cores / okteto_system_node_cpu_requested_cores) * 100",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "Time series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Number of nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    { "expr": "okteto_system_node" }
   ]
  },
  {
   "title": "Nodes CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    { "expr": "okteto_system_node_cpu_cores", "legendFormat": "{{__name__}}-{{node_name}}" },
    {
     "expr": "okteto_system_node_cpu_requested_cores",
     "legendFormat": "{{__name__}}-{{node_name}}"
    },
    {
     "expr": "okteto_system_node_cpu_usage_cores",
     "legendFormat": "{{__name__}}-{{node_name}}"
    }
   ]
  },
  {
   "title": "Nodes memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "okteto_system_node_memory_bytes / 1000000000"
    },
    {
     "expr": "okteto_system_node_memory_requested_bytes / 1000000000"
    },
    {
     "expr": "okteto_system_node_memory_usage_bytes / 1000000000"
    }
   ]
  }
 ]
}